### ISSUE TITLE
Cannot update it on wp. Most of the time via FTP

### ISSUE THREAD

**Issue by ronoliverclarin** [PayMaya/PayMaya-Checkout-WooCommerce-Plugin#1]
I tried to add it via wp admin dashboard but always failed or maybe I'm using shared server. But, It works when I use the FTP method.

**Comment by lordzden** [comment]
I am planning to use PayMaya on Woocommerce. Is it working? I mean I see that this plugin has no current updates.

**Comment by wawimundo** [comment]
@lordzden Yes, it is working. We are currently updating it, please expect an update next week.

**Comment by wawimundo** [comment]
@ronoliverclarin Sorry I just saw your comment. Most of the time, it is a permission issue. Most shared servers do not allow the application like WordPress to write directly to the file system for security purposes.
